# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20160711_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='players',
        ),
        migrations.RemoveField(
            model_name='race',
            name='results',
        ),
        migrations.AddField(
            model_name='race',
            name='player_a',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='player_b',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='race_time_a',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='race_time_b',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.IntegerField(default=250),
        ),
    ]
