# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20160721_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_time_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_time_b',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
