# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20160721_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='player_a',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='race',
            name='player_b',
            field=models.CharField(default='', max_length=255),
        ),
    ]
