# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20160725_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='race',
            name='first_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_round', to='game.Event'),
        ),
        migrations.AddField(
            model_name='race',
            name='second_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_round', to='game.Event'),
        ),
    ]
