# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2016-08-10 09:55:34.819491'),
            preserve_default=False,
        ),
    ]
